name: Doxygen doc

on:
  push:
    branches:
      - master

jobs:
  doxygen:
    runs-on: ubuntu-latest
    container: gradden/mosze-doxy:latest
    steps:
      - uses: actions/checkout@master
      - run: make documentation
      - name: Push git subdir as branch

        uses: s0/git-publish-subdir-action@v2.4.0

        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: DOCS/html
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
