name: Google test

on: push


jobs:
  build:
    runs-on: ubuntu-latest
    container: gradden/test:latest
    steps:
      - name: Build Enviroment
        run: cd /usr/src/gtest && cmake CMakeLists.txt && make && ln -st /usr/lib/ /usr/src/gtest/libgtest.a && ln -st /usr/lib/ /usr/src/gtest/libgtest_main.a
      - uses: actions/checkout@v2      
      - name: CmakeList
        run: cd test && cmake CMakeLists.txt && make
      - name: Permissions
        run:  chmod +x test/unit_test.cpp
      - run: g++-10 -std=c++17 *.cpp -lstdc++fs -o unit_test
      - name: Run test
        run: make gtest
