name: testworkflow

on:
  push

jobs:
  build:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: g++-10 -std=c++17 *.cpp -lstdc++fs
      - run: make io_diff_check
      - name: Install tools
        run: sudo apt-get install -y valgrind cppcheck
      - name: Cppcheck report
        run: make sca
      - name: Artifacting
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: ./report.txt 
      - name: Cppchecks
        run: make sca_warning
      - name: Gplusplus Wall
        run: g++ -Wall -Werror *.cpp
      - name: Valgrind
        run: make memtest
